apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-deployment
  labels:
    app: my-deploy-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-deploy-api
  template:
    metadata:
      labels:
        app: my-deploy-api
    spec:
      containers:
      - name: my-deploy-api
        image: danielsolislerma/image_fraud:latest
        ports:
        - containerPort: 8000
      - name: tests-api
        image: danielsolislerma/image_tests:latest
        env:
        - name: ENV_MACH
          value: "kubernetes"
        ports:
        - containerPort: 5000
