apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: my-deploy-api
spec:
  type: ClusterIP
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 8000
  selector:
    app: my-deploy-api
